apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: monitoring
  labels:
    app: api-gateway
    release: monitoring  # Must match Prometheus operator's label selector
spec:
  selector:
    matchLabels:
      app: api-gateway
      component: metrics
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
