apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trip-service
  namespace: monitoring
  labels:
    app: trip-service
    release: monitoring
spec:
  selector:
    matchLabels:
      app: trip-service
      component: metrics
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
