apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
  labels:
    environment: production
data:
  ENVIRONMENT: "production"
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
  GATEWAY_HTTP_ADDR: ":8081"
  STRIPE_SUCCESS_URL: "https://web.mishrahub.com?payment=success"
  STRIPE_CANCEL_URL: "https://web.mishrahub.com?payment=cancel"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
