# cluster-secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.mishrahub.com"
      path: "kv/org"
      version: "v2"
      auth:
        kubernetes:
          role: external-secrets-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
