apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: frontend-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    remoteRef:
      key: kv/org/prod/frontend
      property: stripe-publishable-key
