apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: kv/org/prod/mongodb
        property: uri
