apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/org/prod/rabbitmq
        property: username
    - secretKey: password
      remoteRef:
        key: kv/org/prod/rabbitmq
        property: password
    - secretKey: uri
      remoteRef:
        key: kv/org/prod/rabbitmq
        property: uri
