apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: prod
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: grpc
    port: 9004
    targetPort: 9004
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
