apiVersion: v1
kind: Service
metadata:
  name: payment-service-canary
  namespace: prod
  labels:
    app: payment-service
    role: canary
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: grpc
    port: 9004
    targetPort: 9004
    protocol: TCP
