apiVersion: v1
kind: Service
metadata:
  name: api-gateway-canary
  namespace: prod
  labels:
    app: api-gateway
    role: canary
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
