apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: driver-service
  namespace: prod
  labels:
    app: driver-service
    environment: production
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: us-central1-docker.pkg.dev/uplifted-woods-471510-b7/ride-sharing/driver-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
          name: grpc
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JAEGER_ENDPOINT
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: uri
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 5
  strategy:
    canary:
      canaryService: driver-service-canary
      stableService: driver-service
      steps:
      - setWeight: 20
      - pause: {duration: 2m}
      - setWeight: 40
      - pause: {duration: 2m}
      - setWeight: 60
      - pause: {duration: 2m}
      - setWeight: 80
      - pause: {duration: 1m}
      maxSurge: "25%"
      maxUnavailable: 0
