apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: prod
  labels:
    app: driver-service
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
  - name: grpc
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
