apiVersion: v1
kind: Service
metadata:
  name: driver-service-canary
  namespace: prod
  labels:
    app: driver-service
    role: canary
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
  - name: grpc
    port: 9092
    targetPort: 9092
    protocol: TCP
