apiVersion: v1
kind: Service
metadata:
  name: trip-service-canary
  namespace: prod
  labels:
    app: trip-service
    role: canary
spec:
  type: ClusterIP
  selector:
    app: trip-service
  ports:
  - name: grpc
    port: 9093
    targetPort: 9093
    protocol: TCP
