apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: prod
  labels:
    app: trip-service
spec:
  type: ClusterIP
  selector:
    app: trip-service
  ports:
  - name: grpc
    port: 9093
    targetPort: 9093
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
