apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: prod
  labels:
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
    protocol: TCP
  - name: collector
    port: 14268
    targetPort: 14268
    protocol: TCP